### ISSUE TITLE
Ai player is not working

### ISSUE THREAD

**Issue by cloudjanak** [7imbrook/Scrabble-Player#1]
can i get all possiable moves that can be played on the current board with starting position and direction
for example you can check below web-site
http://www.lexicalwordfinder.com/?game=Words_With_Friends&layout=1&tiles=gtsfsdf&board=----------------------------------------------------------------------------------------------------------------hello------------------------------------------------------------------------------------------------------------&lexicon=wwf

**Comment by 7imbrook** [comment]
Project is discontinued
